name: 'build-docker'
description: 'Builds the Docker container'
inputs:
  docker-path:
    description: "The path to the docker directory"
    required: false
    default: docker
outputs:
  artifact-path:
    description: "The generated artifact filepath"
    value: ${{ steps.package-artifact.outputs.artifact-path }}
runs:
  using: "composite"
  steps:
    - id: build-rootfs
      run: tar --cd ${{ inputs.docker-path }}/rootfs -czf ../rootfs.tar.gz ./
      shell: bash
    - run: tree -a .
      shell: bash
    - id: build-docker
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.docker-path }}
        platforms: linux/amd64,linux/arm64
        tags: ${{ github.event.repository.name }}
        outputs: type=tar,dest=./docker-image.tar
    - run: tree -a .
      shell: bash
    - id: package-artifact
      run: |
        cp ./docker/.docker-username ./
        gzip ./docker-image.tar
      shell: bash