name: release-docker
description: Releases the docker image to the appropriate channel
inputs:
  docker-username:
    description: The Docker username used for releasing the image
    required: true
  docker-token:
    description: The Docker token used for releasing the image
    required: true
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
runs:
  using: composite
  steps:
    - id: release-docker
      shell: bash
      run: |
        export DOCKER_USERNAME=$(echo ${{ inputs.docker-username }} | tr '[:upper:]' '[:lower:]') # making sure docker username is lower case
        export DOCKER_PASSWORD=${{ inputs.docker-token }}
        (cd ${{ inputs.release-dir }}; npx semantic-release)
    