name: release-docker
description: Releases the docker image to the appropriate channel
inputs:
  docker-token:
    description: The Docker token used for releasing the image
    required: true
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
runs:
  using: composite
  steps:
    - id: get-image-tag
      uses: ./.github/actions/helper/docker-image-tag
    - id: release-docker
      shell: bash
      run: |
        export DOCKER_USERNAME=${{ steps.get-image-tag.outputs.image-namespace }}
        export DOCKER_PASSWORD=${{ inputs.docker-token }}
        (cd ${{ inputs.release-dir }}; npx semantic-release)
    - id: clean-tag
      shell: bash
      run: git push --delete origin $(git describe --tags --abbrev=0)