name: "CodeQL Scan"
# Continuous CodeQL scans, to catch any potential security issues

on:
  push:
  schedule:
    - cron: '30 1 * * 0'

permissions:
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2