name: 'Build icloud-photos-sync artifacts'
description: 'Builds the JS application'
outputs:
  artifact-file:
    description: "The generated npm-pack filename"
    value: ${{ steps.npm-pack.outputs.path }}
runs:
  using: "composite"
  steps:
    - run: cp ./README.md ./CHANGELOG.md ./LICENSE ./app/
      shell: bash
    - run: (cd ./app; npm ci)
      shell: bash
    - run: (cd ./app; npm run build)
      shell: bash
    - id: npm-pack
      run: echo "path=$(cd ./app; npm pack)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo $GITHUB_OUTPUT
      shell: bash