name: 'build-app'
description: 'Builds the JS application'
inputs:
  app-path:
    description: "The path to the app directory"
    required: false
    default: app
outputs:
  artifact-path:
    description: "The generated npm-pack filepath"
    value: ${{ steps.npm-pack.outputs.artifact-path }}
runs:
  using: "composite"
  steps:
    - run: cp ./README.md ./CHANGELOG.md ./LICENSE ${{ inputs.app-path }}/
      shell: bash
    - run: (cd ${{ inputs.app-path }}; npm ci)
      shell: bash
    - run: (cd ${{ inputs.app-path }}; npm run build)
      shell: bash
    - id: npm-pack
      run: echo "artifact-path='${{ inputs.app-path }}/$(cd ${{ inputs.app-path }}; npm pack)'" >> $GITHUB_OUTPUT
      shell: bash
    - run: ls -al ${{ inputs.app-path }}
      shell: bash