name: 'build-app'
description: 'Builds the JS application'
inputs:
  app-path:
    description: "The path to the app directory"
    required: false
    default: app
outputs:
  artifact-path:
    description: "The generated npm-pack filepath"
    value: ${{ steps.npm-pack.outputs.artifact-path }}
runs:
  using: "composite"
  steps:
    - id: setup
      run: cp ./README.md ./CHANGELOG.md ./LICENSE ${{ inputs.app-path }}/
      shell: bash
    - id: npm-ci
      run: (cd ${{ inputs.app-path }}; npm ci)
      shell: bash
    - id: npm-build
      run: (cd ${{ inputs.app-path }}; npm run build)
      shell: bash
    - id: npm-pack
      run: |
        fileName=$(cd ${{ inputs.app-path }}; npm pack)
        echo "artifact-path=${{ inputs.app-path }}/$fileName" >> $GITHUB_OUTPUT
      shell: bash
    - run: ls -al ${{ inputs.app-path }}
      shell: bash