name: release-github
description: Pushes the git tag and updates Github appropriately
inputs:
  gh-token:
    description: The GH token used for performing the release
    required: true
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
  
runs:
  using: composite
  steps:
    - id: release-github
      shell: bash
      run: |
        export GH_TOKEN=${{ inputs.gh-token }}
        (cd ${{ inputs.release-dir }}; npx semantic-release)