name: release-github
description: Pushes the git tag and updates Github appropriately
inputs:
  gh-token:
    description: The GH token used for performing the release
    required: true
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
outputs:
  release-url:
    description: The URL to the created release
    value: https://github.com/${{ steps.get-git-metadata.outputs.owner }}/${{ steps.get-git-metadata.outputs.name }}/releases/tag/${{ steps.get-git-metadata.outputs.version }}
  
runs:
  using: composite
  steps:
    - id: release-github
      shell: bash
      run: |
        export GH_TOKEN=${{ inputs.gh-token }}
        (cd ${{ inputs.release-dir }}; npx semantic-release)
    - id: get-git-metadata
      uses: ./.github/actions/helper/git-metadata