name: 'build-docker-setup'
description: 'Sets up the environment for the docker build action'
inputs:
  docker-path:
    description: "The path to the docker directory"
    required: false
    default: docker
runs:
  using: "composite"
  steps:
    - id: setup-quemu
      uses: docker/setup-qemu-action@v2
    - id: setup-buildx
      uses: docker/setup-buildx-action@v2