name: git-metadata
description: Reads and returns git metadata
outputs:
  version:
    description: The latest version, based on the available git tag
    value: ${{ steps.get-config.outputs.version }}
  name:
    description: The name of the git repository
    value: ${{ steps.get-config.outputs.name }}
  owner:
    description: The name of the git repository owner
    value: ${{ steps.get-config.outputs.owner }}
runs:
  using: "composite"
  steps:
    - id: get-config
      shell: bash
      run: |
        echo "owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
        echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT