name: 'version-bump'
description: 'Version bumps the repository to the next <major>, <minor>, or <patch> version.'
inputs:
  version-bump-type:
    description: "The type of version bump. Either <major>, <minor>, or <patch>"
    required: true
  release-type:
    description: "The type of release. Either <nightly>, <beta> or empty"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' 
        cache-dependency-path: ${{ inputs.docs-path }}
    - id: setup-pip
      shell: bash
      run: pip install bump2version
    - id: get-config
      shell: bash
      run: | 
        echo "docs-dir=$(grep -oP "docs_dir: '\K.+'" ${{ inputs.docs-path }}/mkdocs.yml | head -c-2)" >> $GITHUB_OUTPUT
    - id: setup-fs
      shell: bash
      run: cp ./README.md ./CHANGELOG.md ./LICENSE ${{ inputs.docs-path }}/${{ steps.get-config.outputs.docs-dir }}/