site_name: iCloud Photos Sync
site_url: https://steilerdev.github.io/icloud-photos-sync/
site_description: Documentation for icloud-photos-sync by steilerDev
site_author: Frank Steiler
copyright: steilerDev
repo_url: https://github.com/steilerDev/icloud-photos-sync
edit_uri: ""
nav:
  - 'Home': README.md
  - 'Get Started': get-started.md
  - 'Changelog': CHANGELOG.md

theme:
  name: material
  logo: assets/icloud-photos-sync.svg
  favicon: assets/icloud-photos-sync.svg
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features: 
    - content.tabs.link
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
plugins:
  - search