name: release-docker-setup
description: Sets up the docker release environment
inputs:
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
  artifact-name:
    description: The name of the uploaded docker artifact
    required: false
    default: docker-artifact
runs:
  using: composite
  steps:
    - id: get-image-tag
      uses: ./.github/actions/helper/docker-image-tag
    - id: setup-fs
      shell: bash
      run: |
        mkdir ${{ inputs.release-dir }}
        # Copy release configurations
        cp ${{ github.action_path }}/../docker-release-config/package.json \
          ${{ github.action_path }}/../docker-release-config/package-lock.json \
          ${{ github.action_path }}/../common.releaserc.json \
          ${{ github.action_path }}/../node-version \
          ${{ inputs.release-dir }}/

        # Dynamically adjust image tag within .releaserc.json
        cat ${{ github.action_path }}/../docker-release-config/releaserc.json |\
          jq 'del(.plugins[0][1].name)' |\
          jq '.plugins[0][1].name.namespace = "${{ steps.get-image-tag.outputs.image-namespace }}"' |\
          jq '.plugins[0][1].name.repository = "${{ steps.get-image-tag.outputs.image-repository }}"' |\
          jq '.plugins[0][1].name.tag = "${{ steps.get-image-tag.outputs.image-tag }}"' |\
          sponge ${{ inputs.release-dir }}/.releaserc.json
    - id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ inputs.release-dir }}/node-version
        cache: 'npm'
        cache-dependency-path: ${{ inputs.release-dir }}
    - id: setup-npm
      shell: bash
      run: (cd ${{ inputs.release-dir }}; npm ci)
    - id: download-docker-artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: docker-artifact
    - id: setup-docker-artifact
      shell: bash
      run: docker load --input docker-artifact/docker-amd64.tar.gz