# download docker artifacts & load them
name: release-docker-setup
description: Sets up the docker release environment
inputs:
  release-dir:
    description: Directory, where the semantic release binary and configuration is located
    required: false
    default: release
  artifact-name:
    description: The name of the uploaded docker artifact
    required: false
    default: docker-artifact
runs:
  using: composite
  steps:
    - id: setup-fs
      shell: bash
      run: |
        mkdir ${{ inputs.release-dir }}
        cp ${{ github.action_path }}/../docker-release-config/.releaserc.json \
          ${{ github.action_path }}/../docker-release-config/package.json \
          ${{ github.action_path }}/../docker-release-config/package-lock.json ${{ inputs.release-dir }}
    - id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version-file: ${{ github.action_path }}/../node-version
        cache: 'npm'
        cache-dependency-path: ${{ inputs.release-dir }}
    - id: setup-npm
      shell: bash
      run: (cd ${{ inputs.release-dir }}; npm ci)
    - id: download-docker-artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: docker-artifact
    - id: setup-docker-artifact
      shell: bash
      run: docker load --input docker-artifact/docker-amd64.tar.gz
