
name: '[action] bump release'
run-name: '[action] ${{ inputs.bump-type }} release bump, triggered by @${{ github.actor }}'
# This workflow bumps the release and opens a PR (in case beta or production release bumps were selected)

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Select which type of version bump you want to perform'
        required: true
        default: 'nightly'
        type: choice
        options:
        - nightly-major
        - nightly-minor
        - nightly-patch
        - nightly
        - beta
        - production

permissions:
  contents: write
  pull-requests: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: setup/checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: check/correct-branch
        if: github.ref != 'refs/heads/dev'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than dev"
          exit 1
      - name: check/version
        id: check-version
        uses: ./.github/actions/version/check
      - name: check/correct-order
        run: |
          if [[ ${{ steps.check-version.outputs.beta }} == 'true' && ${{ inputs.bump-type }} == 'nightly' ]]; then
            echo "Illegal transition from beta to nightly"
            exit 1
          fi

          if [[ ${{ steps.check-version.outputs.production }} == 'true' && ${{ inputs.bump-type }} == 'nightly' ]]; then
            echo "Illegal transition from production to nightly"
            exit 1
          fi

          if [[ ${{ steps.check-version.outputs.production }} == 'true' && ${{ inputs.bump-type }} == 'beta' ]]; then
            echo "Illegal transition from production to beta"
            exit 1
          fi
      - name: check/existing-pr
        run: |
          gh pr list --json --label release-bump
      - name: action/version-bump
        uses: ./.github/actions/version/bump
        id: version-bump
        with:
          version-bump-type: ${{ inputs.bump-type }}
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: release bump to ${{ steps.version-bump.outputs.new-version }}
      - name: pull-request
        run: |
          gh pr create -B main -H dev \
            --title '${{ steps.check-version.outputs.main-version }} → ${{ steps.version-bump.outputs.new-version }}' \
            --body '${{ inputs.bump-type }} release bump from ${{ steps.check-version.outputs.main-version }} to ${{ steps.version-bump.outputs.new-version }}, triggered by @${{ github.actor }}' \
            --label ${{ inputs.bump-type }}
            --label release-bump
        env:
            GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}