# Bumps the version to beta (or bumps the current beta version), and opens PR against main

name: 'Action: Bump release'
# This workflow will run on every push containing a tag, that is matching version naming
# If the app builds and passes tests, it will release to the production channel (Docker's 'latest' tag, npm release...)

on:
  workflow_call:
    inputs:
      bump-type:
        description: 'Select which type of version bump you want to perform'
        required: true
        default: 'nightly'
        type: choice
        options:
        - nightly-major
        - nightly-minor
        - nightly-patch
        - nightly
        - beta
        - production

permissions:
  contents: write
  pull-requests: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: setup/checkout
        uses: actions/checkout@v3
      - name: action/version-bump
        uses: ./.github/actions/version-bump
        id: version-bump
        with:
          version-bump-type: ${{ inputs.bump-type }}
      - name: commit
        id: auto-commit-tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Version bump to ${{ steps.version-bump.outputs.new-version }}
      - name: Create Pull Request
        if: inputs.bump-type == "beta" || inputs.bump-type == "production"
        uses: peter-evans/create-pull-request@v5
        with:
          base: dev
          title: Release bump to ${{ steps.version-bump.outputs.new-version }}
          body: This PR bumps the release to ${{ steps.version-bump.outputs.new-version }}
          labels: "beta"