name: Deploy artifacts
# This workflow will deploy the requested artifacts

on:
  workflow_call:
    inputs:
      targets:
        description: 'An array of deployment targets. Will be read using fromJSON(). Allowed values: ["npm", "unit"]'
        required: true
        type: string
    #secrets:

jobs:
  npm:
    runs-on: ubuntu-latest
    if: contains(fromJSON(inputs.artifacts), 'npm'))
    steps:
      - run: echo "deploying to npm"