name: Base debugging workflow

on: [push]

jobs:
  gen-app-artifacts:
    name: "Generate app-artifacts"
    uses: ./.github/workflows/gen-app-artifacts.yml
    #secrets: inherit
    #permissions: {}
