name: Base debugging workflow

on: [push]
    #secrets: inherit
    #permissions: {}

jobs:
 
  gen-artifacts:
    name: gen-artifacts
    uses: ./.github/workflows/gen-artifacts.yml
    with:
      artifacts: '["docker", "changelog"]'
