name: 'Event: Push to {dev}'
run-name: 'Event (Push to {dev}): ${{ github.event.head_commit.message }}'
# Upon receiving a push to dev, this workflow will deploy the dev branch to the nightly channel

on: 
  push:
    branches: # Run on every push to dev
      - 'dev'
    tags-ignore:
      - '**'

jobs:
  check-version:
    name: check-version
    runs-on: ubuntu-latest
    outputs: ## Only continue run if we are on nightly
      nightly: ${{ steps.check-version.outputs.nightly }}
    steps:
      - name: setup/checkout
        uses: actions/checkout@v3
      - name: check-version
        id: check-version
        uses: ./.github/actions/version/check

  build-artifacts:
    name: build-artifacts
    needs: check-version
    if: needs.check-version.outputs.nightly == 'true'
    uses: ./.github/workflows/artifacts_build.yml
    with:
      artifacts: '["app", "docker"]'

  test-artifacts:
    name: test-artifacts
    needs: build-artifacts
    uses: ./.github/workflows/artifacts_test.yml
    with:
      methods: '["unit"]'
    
  deploy-artifacts:
    name: deploy-artifacts
    needs: test-artifacts
    uses: ./.github/workflows/artifacts_deploy.yml
    with:
      targets: '["npm", "docker"]'