name: '[event] push to {dev/beta}'
run-name: '[event] push to {${{ github.ref_name }}}: ${{ github.event.head_commit.message }}'
# Upon receiving a push to dev or beta, this workflow will deploy to the nightly or beta channel

on: 
  push:
    branches: # Run on every push to dev
      - 'dev'
      - 'beta'
    tags-ignore:
      - '**'

permissions: {}

jobs:
  build-release-artifacts:
    name: build-release-artifacts
    uses: ./.github/workflows/artifacts_build-release.yml
    permissions: {}
    with:
      artifacts: '["app"]'
      release: true
    secrets:
      docker-username: ${{ secrets.docker-username }}
      docker-password: ${{ secrets.docker-password }}
      npm-token: ${{ secrets.npm-token }}