name: Generate wiki-artifact
# Builds the typedoc documentation (used for the Github Wiki) and uploads it as <wiki-artifact>
# NEEDS:
#   Artifacts: <none>
#   Secrets: <none>
# GENERATES:
#   Artifacts: wiki-artifact

on: [workflow_call]

permissions: {}

jobs:
  gen-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: setup/checkout
        uses: actions/checkout@v3
      - name: setup/build-wiki
        uses: ./.github/actions/build/wiki-setup
      - name: action/build-wiki
        uses: ./.github/actions/build/wiki
        id: build-wiki
      - name: upload/wiki-artifact
        uses: actions/upload-artifact@v3
        with:
          name: wiki-artifact
          path: ${{ steps.build-wiki.outputs.artifact-path }}