name: Publish Production Release
run-name: Stage Release (${{ inputs.version }})
# This workflow will run on every push containing a tag, that is matching version naming
# If the app builds and passes tests, it will release to the production channel (Docker's 'latest' tag, npm release...)

workflow_dispatch:
    inputs:
      version:
        description: 'Version string for staged release'
        default: 'v1.0.0-beta'
        required: true

jobs:
  